
# Site settings
title: Saumya Shah
name: Saumya Shah
subtitle: The Curious Go-Getter
email: saumyashah97@gmail.com
description: >
  A personal website about learnings I discover in my journey.
baseurl: ""
url: "https://sampshah.github.io"
username: sampshah
github_username:  Saumya-Shah
disqus_shortname: saumya-1
permalink: :title
cover: "/assets/header_image.jpg"
logo: "/assets/ss-logo.jpg"
avatar: "/assets/headshot.jpg"
ga_tracking_id: "UA-82647777-1"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Saumya Shah"


# External gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

exclude:
  - "/vendor/"

# Collections
collections:
  - talks

#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts

social:

  - name: Quora
    icon: quora
    username: Saumya-Shah-2
    url: https://www.quora.com/profile/Saumya-Shah-2
    desc: Follow me on Quora
    share: true

  - name: GitHub
    icon: github
    username: Saumya-Shah
    url: https://github.com/Saumya-Shah
    desc: Fork me on GitHub
    share: true

  - name: LinkedIn
    icon: linkedin
    username: Saumya Shah
    url: https://www.linkedin.com/in/saumya-shah-587574163/
    desc: Connect with me on LinkedIn
    share: true


# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/ss-logo.jpg"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/jpg"

    twitter_image: "/assets/ss-logo.jpg"

    os_repo: "https://github.com/sampshah/sampshah.github.io"
    os_rcs_type: "git"
    os_src: "git@github.com:sampshah.github.io.git"
